### ISSUE TITLE
Merge this repo into Jay's repo

### ISSUE THREAD

**Issue by Upperstage** [bflemi3/acr-configurator#7]

**Comment by bflemi3** [comment]
I'd like to talk more about this. I'm not sure I agree since the front end doesn't need to be coupled to the backend to work. Ie: we could stand up an apache server for the front end and still have the backend running separately on the same domain.

**Comment by Upperstage** [comment]
OK - np.  I thought it would be easier for Jim, but if it doesn't make sense then OI'll close this.
